# Copyright (c) 2024 INVAP, open@invap.com.ar
# SPDX-License-Identifier: AGPL-3.0-or-later OR Fundacion-Sadosky-Commercial

[package]
name = "rt-monitor-rust-example-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rt-monitor-rust-example-app"
path = "src/main.rs"
