name = "rust-example-app"
working_directory = "./sandbox/rust-example-app/specification/"
[process]
    format = "graph"
[process.structure]
nodes = [
    ["init", "task"],
    ["to-loop", "operator:seq_composition"],
    ["control-loop-start", "operator:omega_start"],
    ["filtering", "task"],
    ["filtered-sample", "operator:seq_composition"],
    ["conversion", "task"],
    ["measurement", "operator:seq_composition"],
    ["display_chk", "checkpoint"],
    ["control-loop-end", "operator:omega_end"]
]
edges = [
    ["init","to-loop"],
    ["to-loop","control-loop-start"],
    ["control-loop-start","filtering"],
    ["filtering","filtered-sample"],
    ["filtered-sample","conversion"],
    ["conversion","measurement"],
    ["measurement","display_chk"],
    ["display_chk","control-loop-end"],
    ["control-loop-end", "control-loop-start"]
]
start = "init"


[[process.tasks]]
    name = "init"
    [[process.tasks.pres]]
    [[process.tasks.posts]]
        name = "init_vars"
        format = "protosmt2"
        variables = "(main_realvalue_old:State Int)"
        formula = "(= main_realvalue_old 0)"        # inline formula.
    [[process.tasks.posts]]
        name = "init_fondo_display"
        format = "protosmt2"
        file = "init_fondo_display.protosmt2"       # local file.
#    [[process.tasks.posts]]
#        name = "init_time_bound"
#        format = "protosympy"
#        file = "./sandbox/rust-example-app/specification/init_time_bound"       # relative path to file.
                                                                                      # file is the filename as it is; if it does not have
                                                                                      # extension, so be it.

[[process.tasks]]
    name = "filtering"
    [[process.tasks.pres]]
        name = "filtering_pre"
        format = "protosmt2"
        file = "/Users/clpombo/sandbox/invap-github/rt-monitor/sandbox/rust-example-app/specification/filtering_pre.protosmt2"       # absolute path to file.
    [[process.tasks.posts]]
        name = "filtering_post"
        format = "protosmt2"
        file = "filtering_post.protosmt2"       # local file.
#    [[process.tasks.posts]]
#        name = "filtering_time_bound"
#        format = "protopy"
#        file = "filtering_time_bound.protopy"       # local file.
    [[process.tasks.checkpoints]]
        name = "filtering_chk"
        [[process.tasks.checkpoints.properties]]
            name = "12bitsreading_value"
            format = "protosympy"
            file = "12bitsreading_value.protosympy"       # local file.
#           name = "12bitsreading"
#           format = "protosympy"
#           file = "12bitsreading.protosympy"       # local file.
        [[process.tasks.checkpoints.properties]]
            name = "additionbound"
            format = "protopy"
            file = "additionbound.protopy"       # local file.

[[process.tasks]]
    name = "conversion"
    [[process.tasks.pres]]
        name = "conversion_pre"
        format = "protosmt2"
        file = "conversion_pre.protosmt2"       # local file.
    [[process.tasks.posts]]
        name = "conversion_post"
        format = "protosmt2"
        file = "conversion_post.protosmt2"       # local file.
    [[process.tasks.checkpoints]]

[[process.checkpoints]]
    name = "display_chk"
    [[process.checkpoints.properties]]
        name = "barpointiscorrect"
        format = "protosmt2"
        file = "barpointiscorrect.protosmt2"       # local file.
#    [[process.checkpoints.properties]]
#        name = "bariscorrect"
#        format = "protosmt2"
#        file = "bariscorrect.protosmt2"       # local file.

[components]
    visual = true
    location = "./framework/components/rt_monitor_example_app"
[[components.list]]
    name = "adc"
    component_path = "./framework/components/rt_monitor_example_app"
    component_file = "ex_adc_visual.py"
    component_name = "adc"
    visual_component_file = "ex_adcVisual.py"       # the visual component is assumed to be in the same location as the component
    visual_component_name = "adcVisual"
    visual = true
[[components.list]]
    name = "display"
    component_file = "ex_display.py"
    component_name = "display"
    visual_component_file = "ex_displayVisual.py"
    visual_component_name = "displayVisual"
    visual = true

[[DAP_config]]
type = "task_started"
name = "init"
file = "main.rs"
location = "26,b"
[[DAP_config]]
type = "task_finished"
name = "init"
file = "main.rs"
location = "27,a"
[[DAP_config]]
type = "task_started"
name = "filtering"
file = "main.rs"
location = "40,b"
[[DAP_config]]
type = "task_finished"
name = "filtering"
file = "main.rs"
location = "50,a"
[[DAP_config]]
type = "checkpoint_reached"
name = "filtering_chk"
file = "main.rs"
location = "41,a"
[[DAP_config]]
type = "checkpoint_reached"
name = "display_chk"
file = "main.rs"
location = "60,a"
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "27,a"
variable = "main_realvalue_old"
expression = "realvalue_old"
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "35,a"
variable = "main_addition"
expression = "addition"
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "35,a"
variable = "main_value_{i}"
expression = "value"
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "35,a"
variable = "main_value"
expression = "value"
# Procedimiento para reemplazar:
#
#  main_{g(23*aux)}_value_{i}
#
#  g(23*aux) --> result_1
#  i --> result_2
#
#  main_result_1_value_result_2
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "46,a"
variable = "main_addition"
expression = "addition"
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "46,a"
variable = "main_realvalue"
expression = "realvalue"
[[DAP_config]]
type = "variable_value_assigned"
file = "main.rs"
location = "60,a"
variable = "main_realvalue_old"
expression = "realvalue_old"
[[DAP_config]]
type = "variable_value_assigned"
file = "functions.rs"
location = "12,a"
variable = "measurement_dato_ing"
expression = "dato_ing"
[[DAP_config]]
type = "variable_value_assigned"
file = "functions.rs"
location = "15,a"
variable = "measurement_dato_ing2"
expression = "dato_ing2"
[[DAP_config]]
type = "variable_value_assigned"
file = "functions.rs"
location = "51,a"
variable = "bar_dato_ing"
expression = "dato_ing"
[[DAP_config]]
type = "variable_value_assigned"
file = "functions.rs"
location = "51,a"
variable = "bar_point"
expression = "g"
